 sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /segmentation/
    max_range: 3.0
    point_subsample: 1
    padding_offset: 0.0
    padding_scale: 1.0
    queue_size: 100
    filtered_cloud_topic: filtered_cloud
